package database

import (
	"database/sql"
	"log"

	_ "github.com/mattn/go-sqlite3"
)

var db *sql.DB

func SetDB(database *sql.DB) {
	db = database
}

func CreateTables() error {
	if db == nil {
		log.Fatal("Database not initialized. Call SetDB first.")
	}

		if _, err := db.Exec(`PRAGMA foreign_keys = ON;`); err != nil {
		return err
	}

		if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS SE_CODE_USER_TYPE (
			SE_CODE_USER_TYPE_ID INTEGER PRIMARY KEY,
			DESCR_AR TEXT NOT NULL,
			DESCR_EN TEXT NOT NULL
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS SE_ACCNT (
			SE_ACCNT_ID INTEGER PRIMARY KEY,
			DESCR_AR TEXT NOT NULL,
			DESCR_EN TEXT NOT NULL,
			SE_CODE_USER_TYPE_ID INTEGER NOT NULL,
			FOREIGN KEY (SE_CODE_USER_TYPE_ID) REFERENCES SE_CODE_USER_TYPE(SE_CODE_USER_TYPE_ID)
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS ED_CODE_STATUS_CAT (
			ED_CODE_STATUS_CAT_ID INTEGER PRIMARY KEY,
			DESCR_AR TEXT NOT NULL,
			DESCR_EN TEXT NOT NULL
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS ED_CODE_STATUS (
			ED_CODE_STATUS_ID INTEGER PRIMARY KEY,
			DESCR_AR TEXT NOT NULL,
			DESCR_EN TEXT NOT NULL,
			STATUS_ORDER INTEGER NOT NULL,
			ED_CODE_STATUS_CAT_ID INTEGER NOT NULL,
			FOREIGN KEY (ED_CODE_STATUS_CAT_ID) REFERENCES ED_CODE_STATUS_CAT(ED_CODE_STATUS_CAT_ID)
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS GS_CODE_REQ_STATUS (
			GS_CODE_REQ_STATUS_ID INTEGER PRIMARY KEY,
			DESCR_AR TEXT NOT NULL,
			DESCR_EN TEXT NOT NULL
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS WORKFLOW (
			WORKFLOW_ID INTEGER PRIMARY KEY AUTOINCREMENT,
			WORKFLOW_NAME TEXT NOT NULL UNIQUE,
			DESCRIPTION TEXT
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS WF_VERSION (
			WF_VERSION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
			WORKFLOW_ID INTEGER NOT NULL,
			VERSION INTEGER NOT NULL,
			IS_ACTIVE BOOLEAN NOT NULL DEFAULT 0,
			IS_APPROVED BOOLEAN NOT NULL DEFAULT 0,
			CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
			UNIQUE (WORKFLOW_ID, VERSION),
			FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOW(WORKFLOW_ID) ON DELETE CASCADE
		);
	`); err != nil {
		return err
	}


	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS WF_STATUS (
			WF_STATUS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
			STATUS_ID INTEGER NOT NULL,
			WF_VERSION_ID INTEGER NOT NULL,
			STATUS_NAME TEXT NOT NULL,
			ED_CODE_STATUS_ID INTEGER, -- optional link to SIS status codes
			GS_CODE_REQ_STATUS_ID INTEGER, -- optional link to SIS status codes
			IS_TERMINAL INTEGER NOT NULL DEFAULT 0, -- 1=true
			SUCCESS_PATH INTEGER,
			UNIQUE (STATUS_ID, WF_VERSION_ID),
			FOREIGN KEY (WF_VERSION_ID) REFERENCES WF_VERSION(WF_VERSION_ID) ON DELETE CASCADE,
			FOREIGN KEY (ED_CODE_STATUS_ID) REFERENCES ED_CODE_STATUS(ED_CODE_STATUS_ID),
			FOREIGN KEY (GS_CODE_REQ_STATUS_ID) REFERENCES GS_CODE_REQ_STATUS(GS_CODE_REQ_STATUS_ID)
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS WF_RULE (
			WF_RULE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
			RULE_ID INTEGER NOT NULL,
			WF_VERSION_ID INTEGER NOT NULL,
			FROM_STATUS_ID INTEGER NOT NULL,
			TO_STATUS_ID INTEGER NOT NULL,
			SE_CODE_USER_TYPE_ID INTEGER NOT NULL, -- link to SIS user types
			SE_ACCNT_ID INTEGER,        -- optional link to SIS accounts
			CALENDAR_ID INTEGER,      -- optional link to SIS calendar
			ACTION_BUTTON TEXT NOT NULL, -- e.g., "Approve", "Reject"
			ACTION_FUNCTION TEXT NOT NULL, -- e.g., "approve", "reject", "auto"
			UNIQUE (RULE_ID, WF_VERSION_ID),
			FOREIGN KEY (WF_VERSION_ID) REFERENCES WF_VERSION(WF_VERSION_ID) ON DELETE CASCADE,
			FOREIGN KEY (FROM_STATUS_ID, WF_VERSION_ID) REFERENCES WF_STATUS(STATUS_ID, WF_VERSION_ID) ON DELETE CASCADE,
			FOREIGN KEY (TO_STATUS_ID, WF_VERSION_ID) REFERENCES WF_STATUS(STATUS_ID, WF_VERSION_ID) ON DELETE CASCADE,
			FOREIGN KEY (SE_CODE_USER_TYPE_ID) REFERENCES SE_CODE_USER_TYPE(SE_CODE_USER_TYPE_ID),
			FOREIGN KEY (SE_ACCNT_ID) REFERENCES SE_ACCNT(SE_ACCNT_ID)
		);
	`); err != nil {
		return err
	}

	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS WF_RULE_CONDITION (
			WF_RULE_CONDITION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
			RULE_CONDITION_ID INTEGER NOT NULL,
			WF_VERSION_ID INTEGER NOT NULL,
			RULE_ID INTEGER NOT NULL,
			WF_CONDITION_ID INTEGER NOT NULL,
			TYPE TEXT NOT NULL,        -- e.g., pre, Onclick
			EXPECTED_VALUE BOOLEAN NOT NULL, 
			UNIQUE (RULE_CONDITION_ID, WF_VERSION_ID),
			FOREIGN KEY (RULE_ID, WF_VERSION_ID) REFERENCES WF_RULE(RULE_ID, WF_VERSION_ID) ON DELETE CASCADE,
			FOREIGN KEY (WF_VERSION_ID) REFERENCES WF_VERSION(WF_VERSION_ID) ON DELETE CASCADE,
			FOREIGN KEY (WF_CONDITION_ID) REFERENCES WF_CONDITION(WF_CONDITION_ID) ON DELETE CASCADE
		);
	`); err != nil {
		return err
	}
	// 	FOREIGN KEY (RULE_ID) REFERENCES WF_RULE(RULE_ID) ON DELETE CASCADE,


	if _, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS WF_CONDITION (
			WF_CONDITION_ID INTEGER PRIMARY KEY,
			FUNC_NAME TEXT NOT NULL UNIQUE,
			DESCRIPTION TEXT
		);
	`); err != nil {
		return err
	}

	return nil
}